[package]
name = "waldrive_contracts"
edition = "2024.beta"

[dependencies]
Walrus = { git = "https://github.com/MystenLabs/walrus.git", subdir = "contracts/walrus", rev = "testnet" }

[addresses]
sui = "0x2"
waldrive = "0x0"
